### ISSUE TITLE
Possible hard margin R bug? 

### ISSUE THREAD

**Issue by chenlianMT** [lukasruff/Deep-SVDD#4]
I've noticed when using hard margin for SVDD, you're resetting R after training each epoch according to the outlier ratio nu.

Written in the code comments:
> 'set R to be the (1-nu)-th quantile of distances' 

However, in https://github.com/lukasruff/Deep-SVDD/blob/f3bebc4fdab998e2a9bc71cbffa05fdadf8525ee/src/opt/sgd/train.py#L102
the first component is getting the (1-nu)-th quantile, but the second component is the original R. Won't this make R exploding?

Thanks.

**Comment by lukasruff** [comment]
Hi,

thanks for your comment and sorry for the confusion in this particular line of code you mention.

R is in fact set to be the (1-nu)-th quantile of _distances_, which are computed from the Deep SVDD _scores_.

Since the Deep SVDD scores are defined as

`scores = dist - R`

to obtain a threshold at 0, the radius R is added to the scores in this line to receive the distances from the scores.

Also find the relevant lines that extract the Deep SVDD scores below:

**Definition of Deep SVDD scores:**
https://github.com/lukasruff/Deep-SVDD/blob/f3bebc4fdab998e2a9bc71cbffa05fdadf8525ee/src/opt/sgd/updates.py#L288

**Computing and saving Deep SVDD scores:**
https://github.com/lukasruff/Deep-SVDD/blob/f3bebc4fdab998e2a9bc71cbffa05fdadf8525ee/src/utils/monitoring.py#L53
https://github.com/lukasruff/Deep-SVDD/blob/f3bebc4fdab998e2a9bc71cbffa05fdadf8525ee/src/utils/monitoring.py#L80
